### ISSUE TITLE
Where can I start

### ISSUE THREAD

**Issue by aboyandhis** [venetrius/groupsite#4]
I would like to contribute here. Is someone working on the front end yet?

**Comment by zdbrenda** [comment]
Yes I'm currently working on the front end.

**Comment by aboyandhis** [comment]
OK! Feel free to assign me an issue if you would like me to work on anything.

**Comment by zdbrenda** [comment]
There's also another guy Eric who will be working on the UI.

I finished adding the Projects page (not complete yet) and Eric will be
adding UI to the page, but I am not sure when will he be working on it.

I will let you know if there's something you can help us with.
